In [134]:
%%capture
%matplotlib inline
import os
import sys
import importlib
import matplotlib.pyplot as plt
from io import BytesIO
import tensorflow as tf
import numpy as np
import pandas as pd
from matplotlib.pyplot import imshow
import requests
from PIL import Image, ImageEnhance
from csv import reader
from tqdm.notebook import tqdm
import keras

# first neural network with keras tutorial
from keras.layers import Dropout
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split
from numpy import loadtxt
from sklearn.metrics import accuracy_score
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

tqdm().pandas()

base_folder='/Users/lorneluo/lorne/poolhub/'

csv_path=os.path.join(base_folder,'apps','color_band_training','th.csv')

In [123]:
df=pd.read_csv(csv_path, dtype={'file_path': str,
                                      'white_balance_y': int,
                                      'white_balance_x': int,
                                      'color_y': int,
                                      'color_x': int,
                                      'value_color_r': np.float32,
                                      'value_color_g': np.float32,
                                      'value_color_b': np.float32,
                                      'actual_value': np.float32})
df.head()

dataset = df.values
# split into input (X) and output (Y) variables
X = dataset[:,6:9]/255
Y = dataset[:,5]
X = np.asarray(X).astype(np.float32)
Y = np.asarray(Y).astype(np.float32)
print(X[0])
print(Y)

[0.3019608 0.3529412 0.5882353]
[ 49.  55.  68.  70. 131. 134. 134. 144. 148. 152. 157. 161. 162. 163.
 163. 166. 168. 171. 183. 206. 208. 210. 211. 211. 217. 222. 253. 259.
 308. 472. 620.]


In [124]:
test_size = 0.1

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = test_size)

print(X_train[0])
print(Y_train)

print(X_test)
print(Y_test)

[0.21176471 0.14509805 0.29411766]
[222. 163. 148. 211. 210. 134. 157. 168. 162. 183. 217. 211.  68. 131.
 259. 161. 253. 620. 134. 472.  49. 163. 166. 206. 208.  55. 308.]
[[0.36078432 0.2901961  0.41568628]
 [0.08627451 0.16470589 0.3647059 ]
 [0.27058825 0.23137255 0.39215687]
 [0.49803922 0.36862746 0.54509807]]
[152.  70. 144. 171.]


In [126]:
# define base model
import keras
optimizer = keras.optimizers.Adam(learning_rate=0.001)
loss_function = tf.keras.losses.CategoricalCrossentropy(from_logits=True)

def baseline_model():
	# create model
	model = Sequential()
	model.add(Dense(3, input_dim=3, kernel_initializer='normal', activation='relu'))
	model.add(Dense(1, kernel_initializer='normal'))
	# Compile model
	model.compile(loss='mean_absolute_error', optimizer=optimizer, metrics=['accuracy'])
    # model.compile(loss=loss_function,optimizer=optimizer, metrics=['accuracy'])
	return model

# evaluate model
estimator = KerasRegressor(build_fn=baseline_model, epochs=5000, batch_size=2048, verbose=0)
kfold = KFold(n_splits=10)
results = cross_val_score(estimator, X, Y, cv=kfold)
print(results)
print("Baseline: %.2f (%.2f) MSE" % (results.mean(), results.std()))

[ -36.95346069  -17.74884796  -24.11746407  -59.35799026  -42.94664001
  -44.33726883  -79.12793732  -57.81951904 -122.66366577 -349.28390503]
Baseline: -83.44 (93.08) MSE


In [128]:
estimator.fit(X_train, Y_train )
prediction = estimator.predict(X_test)
# accuracy_score(Y_test, prediction)
print(X_test)
print(Y_test)
print([round(i,1) for i in prediction])

[[0.36078432 0.2901961  0.41568628]
 [0.08627451 0.16470589 0.3647059 ]
 [0.27058825 0.23137255 0.39215687]
 [0.49803922 0.36862746 0.54509807]]
[152.  70. 144. 171.]
[130.93839 103.73477 120.53561 151.7461 ]


In [131]:
print(X_test)
print(Y_test)
print([int(i) for i in prediction])

[[0.36078432 0.2901961  0.41568628]
 [0.08627451 0.16470589 0.3647059 ]
 [0.27058825 0.23137255 0.39215687]
 [0.49803922 0.36862746 0.54509807]]
[152.  70. 144. 171.]
[130, 103, 120, 151]


In [132]:
import random
def generate_random_rgb():
    #Returns a tuple of three RGB values on range [0,1]
    #This is done because  matplotlib.patches take rgb values in range [0,1] -> eg: color=(0,0.5,1)
    #The uniform() method returns a random floating number between the two specified numbers (both included).
    return (random.uniform(0,1), random.uniform(0,1), random.uniform(0,1))

generate_random_rgb()

(0.5165553995318166, 0.9666811572391372, 0.669255285146286)

In [138]:
image = Image.open('/Users/lorneluo/lorne/poolhub/apps/color_band_training/th_training.ipynb')




UnidentifiedImageError: cannot identify image file '/Users/lorneluo/lorne/poolhub/apps/color_band_training/th_training.ipynb'